name: Bug report
description: If you are experiencing an issue, please fill out this form.
title: "[Issue]: "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug form!
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: Describe the bug as accurately as possible.
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug as accurately as possible.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: Please add screenshots if available.
    validations:
      required: false
